FROM mcr.microsoft.com/playwright/python:v1.63.0-noble

WORKDIR /app

ENV PLAYWRIGHT_BROWSERS_PATH=0

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

RUN python -m playwright install chromium

COPY . .

CMD ["sh", "-c", "gunicorn --timeout 300 --bind 0.0.0.0:$PORT app:app"]